### ISSUE TITLE
Feature: refresh library button

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#15]
It will really be helpful to have this button because when i modify my sticker library in local storage than i need to manually back and forth in folders and load it in system.
Having this will save time and effort. 

It will be even more better when this is on keyboard next to recent.
Than refreshing library will be pretty easy
![Screenshot_20211029-200919242~2](https://user-images.githubusercontent.com/54233248/139456441-b2078363-2ee2-42da-afa0-9851d9e93cf1.jpg)

**Comment by FredHappyface** [comment]
Hi thanks for the feature request! :) 

I'll take a look over the coming days but I'm pretty sure this won't be possible due to how permissions work in android 

Not sure if its the same on your device, but tapping the select a directory button opens the last directory I imported for me so that may be an option in the meantime 

Going to add this to the backlog but beware, this may result in a wont-fix if permissions get in the way

**Comment by FredHappyface** [comment]
Sadly this is not possible in testing so I'm going to have to mark this wontfix.

**Comment by FredHappyface** [comment]
Turns out this absolutely was possible in the end. Added a new "reload stickers" button 

![Screenshot_20230823-125214](https://github.com/FredHappyface/Android.EweSticker/assets/41634689/a51380fa-a765-46b1-8028-384827a0d84d)
