### ISSUE TITLE
Feature: Enable "show back button in navbar" by default

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#32]
## Feature
- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe
it is often confusing how to go back to your previous keyboard and going to the settings to change keyboard is a burden, so it make sense to have the button to switch back to keyboard enabled by default

### Describe the solution you'd like
Users can switch back to their keyboard without any additional tweaks

**Comment by FredHappyface** [comment]
I think this is one of those things that can be argued both ways - like most configuration options. As some users may dislike the extra icon by default

**Comment by FredHappyface** [comment]
Ok so this has been open a little while and no-one seems to have jumped on this yet. If this is something you'd like to see then can you please add a thumbs up or something to the feature request? If this doesn't have any discussion/ response over the next month or two then I'll look at closing the issue 

Thanks :)

**Comment by link2xt** [comment]
> I think this is one of those things that can be argued both ways - like most configuration options. As some users may dislike the extra icon by default

What is the use case for this? Switch to EweSticker and use it as the only keyboard, sending only stickers and no letters for days?

**Comment by FredHappyface** [comment]
Not exactly, most Android versions support a keyboard switcher in the navigation bar (often where the old overview menu is) so having this twice might be frustrating for some users (maybe? I don't have a strong opinion hence asking)

But hey if you wanna send stickers non-stop for weeks at a time then who am I to judge 😋

**Comment by link2xt** [comment]
> Not exactly, most Android versions support a keyboard switcher in the navigation bar

The best option would be to somehow autodetect if there is a keyboard switcher already and show the back button if there is none. If it's too hard or impossible, just enable it by default.

Currently EweSticker simply does not work for the basic use case out of the box for users who don't have this button to switch keyboards. They add some stickers in the EweSticker app, switch to EweSticker keyboard from their keyboard (because other keyboards have a keyboard switch button usually) and can't switch back. It can be considered a bug, not a feature request IMO.

**Comment by FredHappyface** [comment]
I wouldn't go as far as calling it a bug but agree with many of the points raised. So I've changed this in the most recent commit. I'll get an update out sometime this month
