### ISSUE TITLE
Bug: trouble importing stickers

### ISSUE THREAD

**Issue by gilbertolazaro92** [FredHappyface/Android.EweSticker#37]
### System info

- OS: Android 10
- Samsung A11

### Describe the bug

Version 2022.01.28. I give the app the path to stickers and doesn't import all image. In some cases I even give the same path more than once and load it a different number or doesn't find anything. I've already tried with previous version 2022.01.03 in the same phone and load all the media. Of course, all compatible formats. All permission are given.

**Comment by FredHappyface** [comment]
Cheers for raising this. Few questions if that's ok? 

- How may stickers are you importing?
- How many stickers in each pack?
- Are there any other files that do not contain stickers that you are trying to import?
- Can you upload a zip of the folder you select so I can try and duplicate? (This way I can work out precisely what isn't working and get a fix done)
- Are you loading from an SD card or something? 

Thanks ☺️

**Comment by gilbertolazaro92** [comment]
How may stickers are you importing? 1013 total
How many stickers in each pack? I´ll send an screenshot
Are there any other files that do not contain stickers that you are trying to import? No, just image in gif, webp and png
Are you loading from an SD card or something? i tried from internal storage and SD card, sometimes load (still not all the stickers) and if i try load again it doesnt load anything
i even tried to load content from only one folder, with one extension and gave the same problem (didnt load them all)
![Screenshot_20220301-132004_MiXplorer](https://user-images.githubusercontent.com/67376405/156226760-77db7586-b7da-488a-a739-978310a3379d.jpg)
[Emojis 1.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163903/Emojis.1.zip)
[Freddie.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163909/Freddie.zip)
[Garfield.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163910/Garfield.zip)
[Guy behind the desk.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163911/Guy.behind.the.desk.zip)
[Leonardo.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163914/Leonardo.zip)
[Memes.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163917/Memes.zip)
[Mr Incre+¡ble.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163921/Mr.Incre%2B.ble.zip)
[Ojitos.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163923/Ojitos.zip)
[Varios.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163927/Varios.zip)
[webp_AuronPlayMayDroid.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163947/webp_AuronPlayMayDroid.zip)
[Zavrozongoh.zip](https://github.com/FredHappyface/Android.EweSticker/files/8163951/Zavrozongoh.zip)

**Comment by gilbertolazaro92** [comment]
thanks for answering

**Comment by FredHappyface** [comment]
Thanks for getting back to me 

- 1013 stickers is within the max limit so that's ok (the max limit is 4096 at the time of writing)
- The pack limit is 128 stickers so I think that is the main cause of your issue (this limit is imposed to prevent the keyboard crashing when loading a pack). The next update is going to do a better job of alerting on errors such as when a pack contains too many stickers. It might be worth upping this limit a little but 120 is pretty standard e.g. on telegram 
- Still need to test the files you've sent (thanks btw, just a little short in time atm)
- Thanks for adding loads of detail, it has helped uncover a bug. Basically the issue where subsequent tries cause inconsistent results is because I forgot to reset a counter. Hopefully the refactoring work I've been doing over the past couple days help with that 
- When you tried loading from one folder I'm assuming that was one with 128+ stickers?

Hope this helps in the meantime. I will be looking at updating the app fairly soon (probably the next couple weeks) with these improvements

**Comment by FredHappyface** [comment]
Ok just to follow up. Tested with your stickers and the total number of stickers is 870 in a development version (limited by the pack size)

**Comment by gilbertolazaro92** [comment]
First of all, thanks for the great job you're doing with this app😃👍. Once I tried to load only one folder and didn't loaded all. It was the meme folder, now I know what happened 😅
